# Generated by Django 4.1.3 on 2022-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.BigIntegerField(default=2000000),
        ),
    ]
