# Generated by Django 4.1.3 on 2023-05-02 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buyorder_company_ipo_profile_sellorder_shortorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='closing_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 0, 0)),
        ),
        migrations.AddField(
            model_name='ipo',
            name='red_herring_prospectus',
            field=models.URLField(default='https://www.google.com/'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 29, 0, 0)),
        ),
    ]
