# Generated by Django 4.1.3 on 2023-02-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolio_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(default='NA', max_length=300)),
                ('description', models.TextField(default='NA', max_length=4000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.IntegerField()),
                ('security_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=8)),
                ('total_no_shares', models.IntegerField(default=0)),
                ('is_listed', models.BooleanField(default=False)),
                ('ipo_lot_min_val', models.IntegerField(default=0)),
                ('ipo_lot_max_val', models.IntegerField(default=0)),
                ('ipo_face_value', models.IntegerField(default=0)),
                ('ipo_lot_size', models.IntegerField(default=0)),
                ('listing_price', models.IntegerField(default=0)),
                ('share_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy_type', models.BooleanField(default=False)),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price_placed', models.IntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPOSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('offer_value', models.IntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
