# Generated by Django 4.1.3 on 2023-01-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolio_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.IntegerField()),
                ('security_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=8)),
                ('total_no_shares', models.IntegerField(default=0)),
                ('is_listed', models.BooleanField(default=False)),
                ('ipo_lot_min_val', models.IntegerField(default=0)),
                ('ipo_lot_max_val', models.IntegerField(default=0)),
                ('ipo_face_value', models.IntegerField(default=0)),
                ('ipo_lot_size', models.IntegerField(default=0)),
                ('listing_price', models.IntegerField(default=0)),
                ('share_price', models.IntegerField(default=0)),
            ],
        ),
    ]
