# Generated by Django 4.1.3 on 2023-02-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_news_security_transaction_iposubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='security_id',
        ),
    ]
