# Generated by Django 4.1.3 on 2023-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipo_closing_date_ipo_red_herring_prospectus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
