# Generated by Django 4.1.3 on 2023-02-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_security_security_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=8)),
                ('total_no_shares', models.IntegerField(default=0)),
                ('is_listed', models.BooleanField(default=False)),
                ('ipo_lot_min_val', models.IntegerField(default=0)),
                ('ipo_lot_max_val', models.IntegerField(default=0)),
                ('ipo_face_value', models.IntegerField(default=0)),
                ('ipo_lot_size', models.IntegerField(default=0)),
                ('listing_price', models.IntegerField(default=0)),
                ('share_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='iposubscription',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
