# Generated by Django 4.1.3 on 2023-02-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_alter_iposubscription_security_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iposubscription',
            old_name='security',
            new_name='company',
        ),
    ]
