# Generated by Django 4.1.3 on 2023-05-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_lot_allowed_ipo_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(blank=True, default=101, unique=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company', to_field='company_id'),
        ),
    ]
