# Generated by Django 4.1.3 on 2023-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ipo_profile_subscription_remove_portfolio_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='cash_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ipo',
            name='final_issue_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ipo',
            name='shares_alloted',
            field=models.IntegerField(default=0),
        ),
    ]
