# Generated by Django 4.1.3 on 2023-03-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_security'),
        ('core', '0008_ipo_cash_received_ipo_final_issue_price_and_more'),
    ]

    operations = [
    ]
