# Generated by Django 4.1.3 on 2023-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ipo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, default=101, max_length=255, unique=True),
        ),
    ]
