# Generated by Django 4.1.3 on 2023-05-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensex', models.FloatField(default=0)),
                ('spread', models.IntegerField(default=0)),
                ('bid_range', models.FloatField(default=0)),
                ('market_on', models.BooleanField(default=True)),
                ('start_news', models.BooleanField(default=True)),
                ('news_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_shares', models.IntegerField(default=0)),
                ('bid_price', models.IntegerField(default=0)),
                ('buy_or_sell', models.BooleanField(default=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ShortOrder',
        ),
    ]
