# Generated by Django 4.1.3 on 2023-05-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_companyshares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='no_of_shares',
        ),
    ]
