# Generated by Django 4.1.3 on 2023-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profile_no_of_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
