# Generated by Django 4.1.3 on 2023-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_traded_price',
        ),
        migrations.AddField(
            model_name='company',
            name='last_traded_prices',
            field=models.JSONField(default=list),
        ),
    ]
