# Generated by Django 4.1.3 on 2023-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_company_last_traded_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_traded_price',
            field=models.IntegerField(default=0),
        ),
    ]
