# Generated by Django 4.1.3 on 2023-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_company_last_traded_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=10000000),
        ),
    ]
