# Generated by Django 4.1.3 on 2023-02-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('description', models.TextField()),
                ('news_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=16)),
                ('isPublished', models.BooleanField(default=False)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
    ]
